import sys
from datetime import datetime
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)


def get_application_root():
    if getattr(sys, "frozen", False):
        return Path(sys.executable).resolve().parent

    return Path(__file__).resolve().parent.parent


def generate_pdf_report(kpis, config):
    project_root = get_application_root()

    output_folder = project_root / "data" / "output"
    output_folder.mkdir(parents=True, exist_ok=True)

    output_file = output_folder / "Report.pdf"

    document = SimpleDocTemplate(str(output_file))

    styles = getSampleStyleSheet()
    elements = []

    # -----------------------------------------
    # Başlık
    # -----------------------------------------

    elements.append(
        Paragraph(
            config["company_name"],
            styles["Title"],
        )
    )

    elements.append(
        Paragraph(
            config["dashboard_title"],
            styles["Heading2"],
        )
    )

    elements.append(
        Spacer(1, 20)
    )

    # -----------------------------------------
    # KPI Tablosu
    # -----------------------------------------

    table_data = [["Metric", "Value"]]

    for key, value in kpis.items():

        if isinstance(value, float):

            if "Margin" in key:
                display = f"{value:.2f}%"
            else:
                display = f'{config["currency"]}{value:,.2f}'

        else:

            if "Quantity" in key:
                display = f"{value}"
            else:
                display = f'{config["currency"]}{value:,}'

        table_data.append(
            [key, display]
        )

    table = Table(
        table_data,
        colWidths=[240, 140],
    )

    table.setStyle(
        TableStyle(
            [
                (
                    "BACKGROUND",
                    (0, 0),
                    (-1, 0),
                    colors.HexColor("#1F4E78"),
                ),
                (
                    "TEXTCOLOR",
                    (0, 0),
                    (-1, 0),
                    colors.white,
                ),
                (
                    "FONTNAME",
                    (0, 0),
                    (-1, 0),
                    "Helvetica-Bold",
                ),
                (
                    "ALIGN",
                    (0, 0),
                    (-1, -1),
                    "CENTER",
                ),
                (
                    "GRID",
                    (0, 0),
                    (-1, -1),
                    0.5,
                    colors.grey,
                ),
                (
                    "BACKGROUND",
                    (0, 1),
                    (-1, -1),
                    colors.beige,
                ),
                (
                    "BOTTOMPADDING",
                    (0, 0),
                    (-1, 0),
                    8,
                ),
            ]
        )
    )

    elements.append(table)

    elements.append(
        Spacer(1, 20)
    )

    # -----------------------------------------
    # Tarih
    # -----------------------------------------

    elements.append(
        Paragraph(
            f"Generated: {datetime.now().strftime('%d.%m.%Y %H:%M')}",
            styles["Normal"],
        )
    )

    elements.append(
        Spacer(1, 12)
    )

    # -----------------------------------------
    # Alt Bilgi
    # -----------------------------------------

    elements.append(
        Paragraph(
            "Generated by ExcelReporter",
            styles["Italic"],
        )
    )

    document.build(elements)